# Generated by Django 4.2.11 on 2024-04-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
