# Generated by Django 4.2.11 on 2024-04-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_ordermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
    ]
