# Generated by Django 4.2.11 on 2024-04-16 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
